[package]
name = "chinese-validator"
version.workspace = true
edition.workspace = true

description = "Core validation logic for Chinese data (address,id_card, license_plate,name, phone, postal_code,qq,username,etc.)"
license = "MIT"  # 也可以使用的其他许可证，如 "Apache-2.0"


repository = "https://github.com/zjqFocus/chinese-validator_rust_crate.git"
homepage = "https://github.com/zjqFocus/chinese-validator_rust_crate"
documentation = "https://docs.rs/chinese-validator-core" 

keywords = ["chinese", "validation","id-card", "license_plate", "postal-code"]
categories = ["data-structures", "text-processing"]
readme = "../README.md"
authors = ["zjqFocus <540007690@qq.com>"] 

[dependencies]
chinese-validator-core = { path = "../chinese-validator-core", version = "0.1.0"  }
chinese-validator-derive = { path = "../chinese-validator-derive", version = "0.1.0"  }